routes/dashboard.php
<?php



Route::group([
    'as' => 'dashboard::',
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'middleware' => ['auth', 'admin'],
], function () {

    /*
    * Dashboard
    */
    Route::get('/', [
        'as' => 'index',
        'uses' => 'MainController@index',
    ]);

    /*
    * Competitions
    */
    Route::resources(['competitions' => 'CompetitionController']);
    Route::post('competitions/{competition}/status/{status}', [
        'as' => 'competitions.status',
        'uses' => 'CompetitionController@changeStatus',
    ]);
    Route::post('competitions/position', [
        'as' => 'competitions.position',
        'uses' => 'CompetitionController@positionUpdate',
    ]);
    Route::post('competitions/tickets/status/live/{ticket}', [
        'as' => 'competitions.ticket.status',
        'uses' => 'CompetitionController@changeTicketStatusToLive',
    ]);

    /**
     * Competition entries
     */
    Route::get('competition-entries', [
       'as' => 'competition-entries.index',
       'uses' => 'CompetitionController@finishedCompetitions'
    ]);
    Route::get('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinnerPage',
    ]);
    Route::post('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinner',
    ]);
    Route::get('competition-entries/{competition_id?}', [
        'as' => 'competition-entries.table',
        'uses' => 'CompetitionEntriesController@table'
    ]);
    Route::get('competition-entries/export/{competition_id?}', [
        'as' => 'competition-entries.export',
        'uses' => 'CompetitionEntriesController@export'
    ]);

    /*
    * Questions
    */
    Route::resources(['questions' => 'QuestionController'], ['except' => ['show']]);

    /*
    * Promo Codes
    */
    Route::resources(['promo-codes' => 'PromoCodeController'], ['except' => ['show']]);

    /*
    * Past Winners
    */
    Route::resources(['past-winners' => 'PastWinnerController'], ['except' => ['show']]);

    /*
    * Live Draws
    */
    Route::resources(['live-draws' => 'LiveDrawController'], ['except' => ['show']]);

    /*
    * Users
    */
    Route::resources(['users' => 'UserController'], ['except' => ['show']]);
    Route::post('users/change-suspend/{user_id}', 'UserController@changeSuspend')->name('users.suspend');
    /*
    * Results
    */
    Route::resources(['results' => 'ResultController'], ['except' => ['show']]);

    /*
    * Order
    */
    Route::resources(['orders' => 'OrderController'], ['only' => ['show', 'index']]);
    Route::post('orders/{competition}/cancel', [
        'as' => 'orders.cancel',
        'uses' => 'OrderController@cancel',
    ]);

    /*
     * Settings
     */
    Route::group([
        'prefix' => 'settings',
        'as' => 'settings.',
    ], function () {
        Route::get('/', 'SettingsController@edit')->name('edit');
        Route::put('/', 'SettingsController@update')->name('update');
    });

    /**
     * Pages
     */
    Route::group([
        'prefix' => 'pages',
        'as' => 'pages.'
    ], function (){
       Route::resource('page', 'PagesController')->except(['show']);
    });

    /*
     * Statistic
     */
    Route::group([
        'prefix' => 'statistics',
        'as' => 'statistics.',
    ], function () {
        Route::get('/', 'StatisticController@index')->name('index');
    });

    /*
     * Trash
     */
    Route::group([
        'prefix' => 'trash',
        'as' => 'trash.',
    ], function () {
        Route::get('', 'TrashController@index')->name('index');
        Route::post('{competition}/restore', 'TrashController@restoreCompetition')->name('restore-competition');
        Route::delete('{competition}', 'TrashController@destroyCompetition')->name('destroy-competition');
    });

    /*
     * Marketing/SMS
     */
    Route::group([
        'prefix' => 'sms',
        'as' => 'sms.',
    ], function () {
        Route::get('/', 'SmsController@index')->name('index');
        Route::get('/history', 'SmsHistoryController@index')->name('history.index');

        Route::post('/{user_id}', 'SmsController1@exclude')->name('exclude');

        Route::get('/create', 'SmsController@create')->name('create');
        Route::get('/store', 'SmsController@store')->name('store');

    });


    /*
     * Analytics
     */
    Route::group([
        'prefix' => 'analytics',
        'as' => 'analytics.',
    ], function () {
        Route::get('/', 'AnalyticsController@edit')->name('edit');
        Route::put('/', 'AnalyticsController@update')->name('update');
    });
});

routes/web.php
<?php

/* Dashboard routes */
include 'dashboard.php';

/**
 * Pages
 */
Route::get('/', [
    'as' => 'main',
    'uses' => 'MainController@main',
]);
Route::post('live-draw/next', [
    'as' => 'live-draw.next',
    'uses' => 'MainController@getNextAvailableLiveDraw',
]);
Route::post('contact', [
    'as' => 'contact.send',
    'uses' => 'MainController@contactForm',
]);
Route::get('live-competitions', [
    'as' => 'live-competitions',
    'uses' => 'MainController@competitions',
]);
Route::get('live-competitions/{slug}', [
    'as' => 'live-competition.show',
    'uses' => 'MainController@competition',
]);
Route::post('live-competitions/{id}/deadline', [
    'as' => 'live-competition.deadline',
    'uses' => 'MainController@checkCompetitionDeadline',
]);
Route::get('winners', [
    'as' => 'winners',
    'uses' => 'MainController@winners',
]);
Route::get('results', [
    'as' => 'results',
    'uses' => 'MainController@results',
]);
Route::get('results/{id?}', [
    'as' => 'result-details',
    'uses' => 'MainController@resultDetails',
]);
Route::get('finished-competitions', [
    'as' => 'finished-competitions',
    'uses' => 'MainController@finishedCompetitions',
]);
Route::get('finished-competition/{slug}', [
    'as' => 'live-competition.finished',
    'uses' => 'MainController@finishedCompetition',
]);
Route::get('page/{slug}', [
    'as' => 'page',
    'uses' => 'MainController@page'
]);

/**
 * User
 */
Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'middleware' => 'auth',
], function () {
    Route::get('', [
        'as' => 'info',
        'uses' => 'UserController@getMainPage',
    ]);

    Route::post('', [
        'as' => 'update-info',
        'uses' => 'UserController@updateUserInfo',
    ]);

    Route::post('update-password', [
        'as' => 'update-password',
        'uses' => 'UserController@updatePassword',
    ]);
});

/**
 * Static pages
 */
Route::group([
    'as' => 'static.',
], function () {
    Route::view('contacts', 'contacts')->name('contacts');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('terms-conditions', 'terms-conditions')->name('terms-conditions');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('privacy-policy', 'privacy-policy')->name('privacy-policy');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('how-to-play', 'how-to-play')->name('how-to-play');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('charity', 'charity')->name('charity');
});

/**
 * Auth
 */
Route::group([
], function () {
    Auth::routes();
    Route::view('user/login', 'login')->name('user.login')->middleware('guest');
    Route::view('user/register', 'register')->name('user.register')->middleware('guest');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::view('reset-password', 'reset-password')->name('reset-password');
    Route::view('forgot-password', 'forgot-password')->name('forgot-password');
});

/**
 * Cart
 */
Route::group([
    'as' => 'cart.',
    'prefix' => 'cart',
    'middleware' => 'auth',
], function () {
    Route::post('add', 'CartController@addItems')->name('add');
    Route::post('delete/{item_id}', 'CartController@deleteItems')->name('delete');
    Route::post('coupon', 'CartController@checkCouponCode')->name('check-coupon');
    Route::post('random', 'CartController@getRandomTickets')->name('random-tickets');
    Route::post('add-random', 'CartController@addRandomItems')->name('add-random');
    Route::get('data','CartController@getData')->name('data');
});
Route::get('cart', 'CartController@getCartPage')->name('cart.view');

/**
 * Order
 */
Route::group([
    'as' => 'order.',
    'prefix' => 'order',
    'middleware' => 'auth',
], function () {
    Route::post('create', 'OrderController@create')->name('create');
    Route::post('delete/{order}', 'OrderController@delete')->name('delete');
    Route::get('details/{order_id}', 'OrderController@detailsPage')->name('details');
    Route::get('checkout', 'OrderController@checkout')->name('checkout');
    Route::get('payment-result/{order_id}', 'OrderController@paymentResult')->name('payment-result')->where(['order_id' => '[0-9]*']);
});

Route::get('orders','OrderController@index')->name('orders')->middleware('auth');

/**
 * E-commerce
 */
Route::view('times-up', 'times-up')->name('times-up');
Route::match(['get', 'post'],'entries',[
    'middleware' => 'auth',
    'as' => 'entries',
    'uses' => 'MainController@entries'
]);

Route::view('change-password', 'change-password')->name('change-password');

resources/views/charity.blade.php
@extends('core.base')

@section('content')

<main>
    <div class="top_banner">
        <div class="opacity-mask d-flex align-items-center" data-opacity-mask="rgba(0, 0, 0, 0.3)">
            <div class="container">
                <h1>Charity</h1>
            </div>
        </div>
    </div>

    <div class="container margin_60_35 charity">
		<div class="row align-items-center">
			<div class="col-md-6">
				<h2>Charities need our help more than ever!</h2>
				<p>Gasmonkey Competitions are pledging to donate a percentage of our profits to support our customers nominated charities.</p>
				<p>If you would like to nominate a charity then simpily rgister on our website and email info@gasmonkeycompetitions.co.uk with your name and nominated registered charity.</p>
			</div>
			<div class="col-md-6">
				<img src="{{asset('img/charity.jpg')}}">
			</div>
		</div>
	</div>
</main>
<!-- /main -->
@endsection

resources/views/contacts.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Contact Us</h1>
        </div>
    </div>
</div>

<div class="container margin_60_35">
                <div class="row">
                <!--Grid column-->
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form action="{{route('contact.send')}}" method="POST" class="js_form-contacts">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                                        <h3>Contact Form</h3>
                                        <div class="form-group">
                                            <label>Name</label>
                                            <input type="text" class="form-control" name="name">
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" class="form-control" name="email" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Message</label>
                                            <textarea class="form-control" rows="3" name="message"></textarea>
                                        </div>
                                        <div class="form-group form-check">
                                            <input type="checkbox" class="form-check-input" id="gdpr" name="policy">
                                            <label class="form-check-label" for="gdpr">I consent in submitting my
                                                details inline with your privacy policy.
                                            </label>
                                        </div>
                                        <input type="hidden" name="recaptcha" id="recaptcha">
                                        <button class="btn_1 full-width" type="submit">Submit</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <h3>FAQ</h3>
                                    <div class="faq">
                                        <div class="question">HOW DO I PURCHASE TICKET NUMBERS?</div>
                                        <div class="answer">Playing is easy, first you need to create an account by clicking here. Once you aree logged into your account navigate to the competition you wish to enter, select your numbers or use our lucky dip, answer the question and proceed to checkout.</div>
                                        <div class="question">WHAT HAPPENS IF THE TIMER RUNS OUT AND ALL NUMBERS ARN'T SOLD?</div>
                                        <div class="answer">Dont worry,  we will always hold a draw for each competition,  we will keep draw date extensions to the minimum, See our <a href="{{route('static.terms-conditions')}}">Terms & Conditions</a> for full details.</div>
                                        <div class="question">HOW DO YOU DRAW THE WINNER OF THE COMPETITION?</div>
                                        <div class="answer">We use our specialist random ball machine in order to pick our competition winner. These draws can be watched live via our facebook page.</div>
                                    </div>
                                    <p class="mt-4"><a href="{{route('static.how-to-play')}}">View more FAQ and how to play instructions.</a></p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->

@endsection
@push('after-scripts')
    @include('parts/_recaptcha')
@endpush

resources/views/finished-competitions.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Finished Competitions</h1>
        </div>
    </div>
</div>

<div class="container margin_60_35 competition-grid">
    <div class="row small-gutters">
        @foreach($competitions as $competition)
            @include('parts/_competition-card')
        @endforeach
    </div>
    <!-- /row -->
    @include('parts/_pagination', ['paginator' => $competitions, 'filter' => $filter])
</div>

@endsection

resources/views/forgot-password.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Forgot Password</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_30">
    <!-- /page_header -->
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-8 offset-md-3">
            <div class="box_account">
                <div class="form_container">
                    <h2>Reset Password</h2>
                    <form action="{{route('password.email')}}" method="post" class="js_form-forgot-password">
                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" class="form-control" placeholder="Email Address" name="email" required="required">
                    </div>
                    <div class="text-center"><button type="submit" class="btn_1 full-width">Reset Password</button></div>
                    </form>
                </div>
                <!-- /form_container -->
                <p class="float-right pt-2">No account yet? <a href="{{route('user.register')}}">Create one here.</a></p>
            </div>
            <!-- /box_account -->
        </div>
    </div>
</div>
<!-- /container -->

@endsection

resources/views/login.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center" data-opacity-mask="rgba(0, 0, 0, 0.3)">
        <div class="container">
            <h1>Login</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_30">
<!-- /page_header -->
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-8 offset-md-3">
            <div class="box_account">
                <div class="form_container">
                    <h2>Login</h2>
                    <form action="{{url('login')}}" method="post">
                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                    <div class="form-group">
                        <label>Username / Email</label>
                         <input type="text" name="login" class="form-control" placeholder="Username / Email" value="{{ old('login') }}" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" placeholder="Password" value="{{ old('password') }}" required>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            @if ($errors->has('username'))
                                <div id="form-status" class="with_error">{{ $errors->first('username') }}</div>
                            @endif
                            @if ($errors->has('email'))
                                <div id="form-status" class="with_error">{{ $errors->first('email') }}</div>
                            @endif
                            @if ($errors->has('recaptcha'))
                                <div id="form-status" class="with_error">{{ $errors->first('recaptcha') }}</div>
                            @endif
                        </div>
                    </div>
                    <input type="hidden" name="recaptcha" id="recaptcha">
                    <div class="text-center"><button type="submit" class="btn_1 full-width">Login</button></div>
                    <div class="row">
                        <div class="col-md-6">
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="{{route('password.request')}}">Forgot Password?</a>
                        </div>
                    </div>
                </div>
                <!-- /form_container -->
                <p class="float-right pt-2">No account yet? <a href="{{route('user.register')}}">Create one here.</a></p>
            </div>
            <!-- /box_account -->
        </div>
    </div>
</div>
<!-- /container -->

@endsection
@push('after-scripts')
    @include('parts/_recaptcha')
@endpush

resources/views/main.blade.php
@extends('core.base')

@section('content')
    @include('parts/_main-blk')

    @include('parts/_competitions')

    @include('parts/_how-to-play')

    @include('parts/_past-winners')

    @include('parts/_about')

@endsection

resources/views/order-details.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Order Details</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_30">
    <div class="row order_wrap">
        <div class="col-md-12">
            <div class="card shadow mb-3">
                @include('orders.parts._order-items-details', ['order' => $order])
            </div>
        </div>
        <div class="col-lg-12">
            <!-- Card -->
            <div class="card mb-3 shadow">
                  @include('orders.parts._order-details', [ 'order' => $order, 'btnLink' => route('user.info') ])
            <!-- Card -->
        </div>
    </div>
</div>

@endsection

resources/views/orders.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Account</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_60_35 account_wrap">
    <div class="row">
        <div class="col-md-3 account_menu">
            <h4 class="d-none d-lg-block">Account Menu</h4>
            <nav class="navbar navbar-expand-lg navbar-light p-0">
                <h4 class="d-lg-none">Account Menu</h4>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#accountnav" aria-controls="accountnav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="accountnav">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('entries*')) active @endif" href="{{route('entries')}}"><i class="ti-ticket"></i> Entries</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('orders*')) active @endif" href="{{route('orders')}}"><i class="ti-shopping-cart"></i> Orders</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('user.info*')) active @endif" href="{{route('user.info')}}"><i class="ti-user"></i> Account Details</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('change-password*')) active @endif" href="{{route('change-password')}}"><i class="ti-lock"></i> Change Password</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{{route('logout')}}"><i class="ti-power-off"></i> Log Out</a>
                        </li>
                        @auth
                            @if(Auth::user() && Auth::user()->isAdmin())
                        <li class="nav-item">
                        <a class="nav-link" href="{{route('dashboard::index')}}"><i class="ti-key"></i> Admin Dashboard</a>
                        </li>
                            @endif
                        @endauth
                    </ul>
                </div>
            </nav>
        </div>
        <div class="col-md-8 order_wrap mt-4">
            <h2>Orders</h2>
            <div class="card mb-3">
                <div class="card-body">
                    <div class="js_tbl-wrap" data-method="GET" data-action="{{url()->current()}}">
                        @include('parts/_orders-table')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/user.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Account</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_60_35 account_wrap">
    <div class="row">
        <div class="col-md-3 account_menu">
            <h4 class="d-none d-lg-block">Account Menu</h4>
                        <nav class="navbar navbar-expand-lg navbar-light p-0">
                <h4 class="d-lg-none">Account Menu</h4>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#accountnav" aria-controls="accountnav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="accountnav">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('entries*')) active @endif" href="{{route('entries')}}"><i class="ti-ticket"></i> Entries</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('orders*')) active @endif" href="{{route('orders')}}"><i class="ti-shopping-cart"></i> Orders</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" href="{{route('user.info')}}"><i class="ti-user"></i> Account Details</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('change-password*')) active @endif" href="{{route('change-password')}}"><i class="ti-lock"></i> Change Password</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{{route('logout')}}"><i class="ti-power-off"></i> Log Out</a>
                        </li>
                        @auth
                            @if(Auth::user() && Auth::user()->isAdmin())
                        <li class="nav-item">
                        <a class="nav-link" href="{{route('dashboard::index')}}"><i class="ti-key"></i> Admin Dashboard</a>
                        </li>
                            @endif
                        @endauth
                    </ul>
                </div>
            </nav>
        </div>
        <div class="col-md-8 order_wrap mt-4">
            <h2>Account Details</h2>
            <div class="card mb-3">
                <div class="card-body">
                    <form action="{{route('user.update-info')}}" method="post" class="js_form-change-user-info">
                        <div class="row">
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>First Name</label>
                                    <input type="text" class="form-control" placeholder="First Name" value="{{$user->first_name}}" name="first_name" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Last Name</label>
                                    <input type="text" class="form-control" placeholder="Last Name" value="{{$user->last_name}}" name="last_name" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Username</label>
                                    <input type="text" class="form-control" id="display-name" name="username" placeholder="{{$user->username}}" disabled>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" placeholder="Email" id="email" value="{{$user->email}}" name="email" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Phone</label>
                                    <input type="text" class="form-control" placeholder="Phone" id="phone" value="{{$user->phone}}" name="phone" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>First Line Address</label>
                                    <input type="text" class="form-control" placeholder="First Line Address" value="{{$user->address}}" name="address" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>City / Town</label>
                                    <input type="text" class="form-control" placeholder="City/Town" value="{{$user->town}}" name="town" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Post Code</label>
                                    <input type="text" class="form-control" placeholder="Post Code" value="{{$user->post_code}}" name="post_code" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group wrap-checkbox">
                                    <input class="form-checkbox" type="checkbox" name="subscription" id="assent" @if($user->subscription) checked @endif>
                                    <label for="assent"><i class="checked-ic"></i><span>Keep me updated with all the news, special offers and discount codes</span></label>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="btn_1 full-width reg" type="submit">Update Details</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection