routes/dashboard.php
<?php



Route::group([
    'as' => 'dashboard::',
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'middleware' => ['auth', 'admin'],
], function () {

    /*
    * Dashboard
    */
    Route::get('/', [
        'as' => 'index',
        'uses' => 'MainController@index',
    ]);

    /*
    * Competitions
    */
    Route::resources(['competitions' => 'CompetitionController']);
    Route::post('competitions/{competition}/status/{status}', [
        'as' => 'competitions.status',
        'uses' => 'CompetitionController@changeStatus',
    ]);
    Route::post('competitions/position', [
        'as' => 'competitions.position',
        'uses' => 'CompetitionController@positionUpdate',
    ]);
    Route::post('competitions/tickets/status/live/{ticket}', [
        'as' => 'competitions.ticket.status',
        'uses' => 'CompetitionController@changeTicketStatusToLive',
    ]);

    /**
     * Competition entries
     */
    Route::get('competition-entries', [
       'as' => 'competition-entries.index',
       'uses' => 'CompetitionController@finishedCompetitions'
    ]);
    Route::get('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinnerPage',
    ]);
    Route::post('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinner',
    ]);
    Route::get('competition-entries/{competition_id?}', [
        'as' => 'competition-entries.table',
        'uses' => 'CompetitionEntriesController@table'
    ]);
    Route::get('competition-entries/export/{competition_id?}', [
        'as' => 'competition-entries.export',
        'uses' => 'CompetitionEntriesController@export'
    ]);

    /*
    * Questions
    */
    Route::resources(['questions' => 'QuestionController'], ['except' => ['show']]);

    /*
    * Promo Codes
    */
    Route::resources(['promo-codes' => 'PromoCodeController'], ['except' => ['show']]);

    /*
    * Past Winners
    */
    Route::resources(['past-winners' => 'PastWinnerController'], ['except' => ['show']]);

    /*
    * Live Draws
    */
    Route::resources(['live-draws' => 'LiveDrawController'], ['except' => ['show']]);

    /*
    * Users
    */
    Route::resources(['users' => 'UserController'], ['except' => ['show']]);
    Route::post('users/change-suspend/{user_id}', 'UserController@changeSuspend')->name('users.suspend');
    /*
    * Results
    */
    Route::resources(['results' => 'ResultController'], ['except' => ['show']]);

    /*
    * Order
    */
    Route::resources(['orders' => 'OrderController'], ['only' => ['show', 'index']]);
    Route::post('orders/{competition}/cancel', [
        'as' => 'orders.cancel',
        'uses' => 'OrderController@cancel',
    ]);

    /*
     * Settings
     */
    Route::group([
        'prefix' => 'settings',
        'as' => 'settings.',
    ], function () {
        Route::get('/', 'SettingsController@edit')->name('edit');
        Route::put('/', 'SettingsController@update')->name('update');
    });

    /**
     * Pages
     */
    Route::group([
        'prefix' => 'pages',
        'as' => 'pages.'
    ], function (){
       Route::resource('page', 'PagesController')->except(['show']);
    });

    /*
     * Statistic
     */
    Route::group([
        'prefix' => 'statistics',
        'as' => 'statistics.',
    ], function () {
        Route::get('/', 'StatisticController@index')->name('index');
    });

    /*
     * Trash
     */
    Route::group([
        'prefix' => 'trash',
        'as' => 'trash.',
    ], function () {
        Route::get('', 'TrashController@index')->name('index');
        Route::post('{competition}/restore', 'TrashController@restoreCompetition')->name('restore-competition');
        Route::delete('{competition}', 'TrashController@destroyCompetition')->name('destroy-competition');
    });

    /*
     * Marketing/SMS
     */
    Route::group([
        'prefix' => 'sms',
        'as' => 'sms.',
    ], function () {
        Route::get('/', 'SmsController@index')->name('index');
        Route::get('/history', 'SmsHistoryController@index')->name('history.index');

        Route::post('/{user_id}', 'SmsController1@exclude')->name('exclude');

        Route::get('/create', 'SmsController@create')->name('create');
        Route::get('/store', 'SmsController@store')->name('store');

    });


    /*
     * Analytics
     */
    Route::group([
        'prefix' => 'analytics',
        'as' => 'analytics.',
    ], function () {
        Route::get('/', 'AnalyticsController@edit')->name('edit');
        Route::put('/', 'AnalyticsController@update')->name('update');
    });
});

routes/web.php
<?php

/* Dashboard routes */
include 'dashboard.php';

/**
 * Pages
 */
Route::get('/', [
    'as' => 'main',
    'uses' => 'MainController@main',
]);
Route::post('live-draw/next', [
    'as' => 'live-draw.next',
    'uses' => 'MainController@getNextAvailableLiveDraw',
]);
Route::post('contact', [
    'as' => 'contact.send',
    'uses' => 'MainController@contactForm',
]);
Route::get('live-competitions', [
    'as' => 'live-competitions',
    'uses' => 'MainController@competitions',
]);
Route::get('live-competitions/{slug}', [
    'as' => 'live-competition.show',
    'uses' => 'MainController@competition',
]);
Route::post('live-competitions/{id}/deadline', [
    'as' => 'live-competition.deadline',
    'uses' => 'MainController@checkCompetitionDeadline',
]);
Route::get('winners', [
    'as' => 'winners',
    'uses' => 'MainController@winners',
]);
Route::get('results', [
    'as' => 'results',
    'uses' => 'MainController@results',
]);
Route::get('results/{id?}', [
    'as' => 'result-details',
    'uses' => 'MainController@resultDetails',
]);
Route::get('finished-competitions', [
    'as' => 'finished-competitions',
    'uses' => 'MainController@finishedCompetitions',
]);
Route::get('finished-competition/{slug}', [
    'as' => 'live-competition.finished',
    'uses' => 'MainController@finishedCompetition',
]);
Route::get('page/{slug}', [
    'as' => 'page',
    'uses' => 'MainController@page'
]);

/**
 * User
 */
Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'middleware' => 'auth',
], function () {
    Route::get('', [
        'as' => 'info',
        'uses' => 'UserController@getMainPage',
    ]);

    Route::post('', [
        'as' => 'update-info',
        'uses' => 'UserController@updateUserInfo',
    ]);

    Route::post('update-password', [
        'as' => 'update-password',
        'uses' => 'UserController@updatePassword',
    ]);
});

/**
 * Static pages
 */
Route::group([
    'as' => 'static.',
], function () {
    Route::view('contacts', 'contacts')->name('contacts');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('terms-conditions', 'terms-conditions')->name('terms-conditions');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('privacy-policy', 'privacy-policy')->name('privacy-policy');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('how-to-play', 'how-to-play')->name('how-to-play');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('charity', 'charity')->name('charity');
});

/**
 * Auth
 */
Route::group([
], function () {
    Auth::routes();
    Route::view('user/login', 'login')->name('user.login')->middleware('guest');
    Route::view('user/register', 'register')->name('user.register')->middleware('guest');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::view('reset-password', 'reset-password')->name('reset-password');
    Route::view('forgot-password', 'forgot-password')->name('forgot-password');
});

/**
 * Cart
 */
Route::group([
    'as' => 'cart.',
    'prefix' => 'cart',
    'middleware' => 'auth',
], function () {
    Route::post('add', 'CartController@addItems')->name('add');
    Route::post('delete/{item_id}', 'CartController@deleteItems')->name('delete');
    Route::post('coupon', 'CartController@checkCouponCode')->name('check-coupon');
    Route::post('random', 'CartController@getRandomTickets')->name('random-tickets');
    Route::post('add-random', 'CartController@addRandomItems')->name('add-random');
    Route::get('data','CartController@getData')->name('data');
});
Route::get('cart', 'CartController@getCartPage')->name('cart.view');

/**
 * Order
 */
Route::group([
    'as' => 'order.',
    'prefix' => 'order',
    'middleware' => 'auth',
], function () {
    Route::post('create', 'OrderController@create')->name('create');
    Route::post('delete/{order}', 'OrderController@delete')->name('delete');
    Route::get('details/{order_id}', 'OrderController@detailsPage')->name('details');
    Route::get('checkout', 'OrderController@checkout')->name('checkout');
    Route::get('payment-result/{order_id}', 'OrderController@paymentResult')->name('payment-result')->where(['order_id' => '[0-9]*']);
});

Route::get('orders','OrderController@index')->name('orders')->middleware('auth');

/**
 * E-commerce
 */
Route::view('times-up', 'times-up')->name('times-up');
Route::match(['get', 'post'],'entries',[
    'middleware' => 'auth',
    'as' => 'entries',
    'uses' => 'MainController@entries'
]);

Route::view('change-password', 'change-password')->name('change-password');

resources/views/parts/_banner-bottom.blade.php
@if(isset($cart) && $cart->getContent()->count())
<div class="container-fluid fixed-bottom">
    <div class="row align-items-center timer_wrap animate__animated animate__backInUp" data-location="{{route('cart.view')}}">
        <div class="col-md-12">
            Your Entries Will Expire In <span class="basket-timer" data-time="{{$cart->getLifeTimeLeft()}}"></span>
        </div>
    </div>
</div>
@endif

resources/views/parts/_body-all.blade.php
{!!  $analytic->body_all !!}

resources/views/parts/_body-checkout.blade.php
{!!  $analytic->body_checkout !!}

resources/views/parts/_competition-card.blade.php
<div class="col-md-4 col-xl-4">
    <div class="grid_item">
        <figure>
            @if(\App\Enums\CompetitionStatusEnum::PAUSED()->is($competition->status))
                <span class="ribbon paused">{{$competition->status}}</span>
            @elseif(\App\Enums\CompetitionStatusEnum::FINISHED()->is($competition->status))
            @elseif(\App\Enums\CompetitionStatusEnum::SOLD_OUT()->is($competition->status))
                <span class="ribbon sold-out">{{$competition->status}}</span>
            @elseif($competition->sale_price)
                <span class="ribbon sale">ON SALE</span>
            @else
            @endif
            @if(! \App\Enums\CompetitionStatusEnum::FINISHED()->is($competition->status))
                <a href="{{route('live-competition.show', $competition->slug)}}">
            @else
                <a href="{{route('live-competition.finished', $competition->slug)}}">
            @endif
                <img class="img-fluid lazy" src="{{$competition->present()->main_image}}" alt="{{$competition->title}}">
            </a>
            @if(! $competition->isFinished())
                <div class="countdown">{{now()->diffInDays($competition->deadline)}} DAYS LEFT</div>
            @else
                <div class="countdown">Finished {{date('d/m/Y \@ H:i', strtotime($competition->deadline))}}</div>
            @endif
        </figure>
        @if(! \App\Enums\CompetitionStatusEnum::FINISHED()->is($competition->status))
                <a href="{{route('live-competition.show', $competition->slug)}}">
        @else
                <a href="{{route('live-competition.finished', $competition->slug)}}">
        @endif
            <h3>{{$competition->title}}</h3>
        </a>
        <div class="row p-2 align-items-center">
            <div class="col-md-12">
                @if(! $competition->isFinished())
                <div class="price_box">
                    <span class="new_price"><span>£</span>{{$competition->sale_price ? formatValue($competition->sale_price) : formatValue($competition->price)}}</span>
                    @if($competition->sale_price)
                    <span class="old_price">£{{formatValue($competition->price)}}</span>
                    @endif
                </div>
                @else
                @endif
            </div>
            
        </div>
    </div>
    <!-- /grid_item -->
</div>

resources/views/parts/_competitions.blade.php
<div class="bg_dark">
<div class="container margin_60_35 competition-grid">
    <div class="main_title">
        <h2>Live Competitions</h2>
        <p>View a list of our live competitions below.</p>
    </div>
    <div class="row small-gutters">
        @foreach($competitions as $competition)
                @include('parts/_competition-card')
        @endforeach
    </div>
    <!-- /row -->
    <div class="row text-center mt-2 mb-2">
        <div class="col-md-12">
            <a class="btn_1" href="{{route('live-competitions')}}" role="button">VIEW ALL COMPETITIONS</a>
        </div>
    </div>
</div>
</div>

resources/views/parts/_forms.blade.php
<!-- Modal -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Login Or Register</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">x</span></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <p>You must be registered to play our competitions. Please login or create an
                            account.</p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                    <a class="btn_1" href="{{route('user.login')}}">Login</a>
                    <a class="btn_1" href="{{route('user.register')}}">Register</a>
            </div>
        </div>
    </div>
</div>
<!-- Modal end -->


<div class="modal fade" id="error-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Error</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">x</span></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <p class="js_tickes-modal-msg">Sorry, you have selected or exceeded the maximum tickets for this competition</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{{--Configm--}}
<div class="modal fade" id="confirm-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>You are sure?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">x</span></button>
            </div>
            <div class="modal-footer">
                <div class="solid-btn">
                    <a class="text-white js_delete-btn-confirm" data-dismiss="modal" aria-label="Close">Yes</a>
                    <a class="text-white" data-dismiss="modal" aria-label="Close">No</a>
                </div>
            </div>

        </div>
    </div>
</div>


{{--3D Secure--}}
<button style="display: none;" class="js_modal-secure-btn"
        data-toggle="modal" data-target="#confirm-secure" ></button>
<div class="modal fade" id="confirm-secure" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content secure-modal-cnt">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">x</span></button>
            </div>
            <div class="modal-form modal-form-secure js_wrap-secure clearfix">
            </div>
        </div>
    </div>
</div>

resources/views/parts/_google-tag-manager.blade.php
@if(session()->exists('google_tag_manager_event'))
    <script>
        window.dataLayer = window.dataLayer || [];
        dataLayer.push(@json(session()->get('google_tag_manager_event')));
    </script>
@endif

resources/views/parts/_header.blade.php
<!-- Header bar area Start -->
<div class="header-bar-area v2">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2 col-md-4 col-6">
                <a class="navbar-brand p-0 m-0" href="{{url('/')}}">
                    <img src="{{asset('img/logo.svg')}}" alt="Logo">
                </a>
            </div>
            <div class="col-lg-10 col-md-8 col-6 text-right">
                <div class="header_menu_wrap">
                    <div class="header_menu">
                        <ul class="main-menu">
                            <li class="nav-item">
                                <a class="nav-link @if(request()->is('/*')) active @endif" href="{{route('main')}}">HOME</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link @if(request()->is('live-competitions*')) active @endif" href="{{route('live-competitions')}}">LIVE COMPETITIONS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link @if(request()->is('winners*')) active @endif" href="{{route('winners')}}">WINNERS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link @if(request()->is('how-to-play*')) active @endif" href="{{route('static.how-to-play')}}">HOW TO PLAY</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link @if(request()->is('charity*')) active @endif" href="{{route('static.charity')}}">CHARITY</a>
                            </li>
                            @foreach($headerLinksPages as $page)
                                <li class="nav-item">
                                    <a class="nav-link @if($page->isCurrent()) active @endif" href="{{$page->present()->link()}}">{{$page->title}}</a>
                                </li>
                            @endforeach
                        </ul>
                        <div class="hamburger-menu">
                            <span class="line-top"></span>
                            <span class="line-center"></span>
                            <span class="line-bottom"></span>
                        </div>
                    </div>
                    <div class="user_option">
                        <ul>
                            <li>
                                @auth
                                <a href="{{route('orders')}}"><i class="header-user"></i></a>
                                @endauth
                                @guest
                                <a href="{{route('user.login')}}"><i class="header-user"></i></a>
                                @endguest
                            </li>
                            <li>
                                <a href="{{route('cart.view')}}" class="header-cart-link"><i class="header-cart"></i><strong>{{$cartItems ?? 0}}</strong></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Header bar area End -->
<!-- Ofcanvas-menu -->
<div class="ofcavas-menu">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link js_menu-mob-i" href="{{route('main')}}">HOME</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js_menu-mob-i" href="{{route('live-competitions')}}">COMPETITIONS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js_menu-mob-i" href="{{route('winners')}}">WINNERS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js_menu-mob-i" href="{{route('static.how-to-play')}}">HOW TO PLAY</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js_menu-mob-i" href="{{route('static.charity')}}">CHARITY</a>
        </li>
        @foreach($headerLinksPages as $page)
            <li class="nav-item">
                <a class="nav-link js_menu-mob-i" href="{{$page->present()->link()}}">{{$page->title}}</a>
            </li>
        @endforeach
    </ul>
</div>
<!-- Ofcanvas-menu END-->
<main>

resources/views/parts/_pagination-ajax.blade.php
@if ($paginator->hasPages())
    <div class="entry_pagination">
        <p><span>{{($paginator->currentPage()-1)*$paginator->perPage()+1}}-{{$paginator->currentPage()*$paginator->perPage()}}</span> of {{$paginator->total()}}</p>
        <ul>
            <li>
                <a class="prev js_btn-prev @if($paginator->onFirstPage()) __disable @endif" data-page="{{$paginator->currentPage()}}" href="{{ $paginator->url($paginator->previousPageUrl()) }}">
                    <i class="ion-ios-arrow-back"></i>
                </a>
            </li>
            <li>
                <a class="next js_btn-next @if(!$paginator->hasMorePages()) __disable @endif" data-page="{{$paginator->currentPage()}}" href="{{ $paginator->nextPageUrl() }}">
                    <i class="ion-ios-arrow-forward"></i>
                </a>
            </li>
        </ul>
    </div>
@endif

resources/views/parts/_pagination.blade.php
@if ($paginator->hasPages())

<div class="pagination__wrapper">
    <ul class="pagination">
        <li class="{{ ($paginator->currentPage() == 1) ? '__disable' : '' }}"><a href="{{ $paginator->url($paginator->currentPage()-1) }}" class="prev" title="previous page">❮</a></li>
        @for ($i = 1; $i <= $paginator->lastPage(); $i++)
            <li>
                <a class="{{ ($paginator->currentPage() == $i) ? ' active' : '' }}"
                   href="{{ $paginator->url($i) }}">{{ $i }}</a>
            </li>
        @endfor
        <li class="{{ ($paginator->currentPage() == $paginator->lastPage()) ? '__disable' : '' }}"><a href="{{ $paginator->url($paginator->currentPage()+1) }}" class="next" title="next page">❯</a></li>
    </ul>
</div>
@endif

resources/views/parts/_past-winners.blade.php
<div class="container margin_60_35">
    <div class="main_title">
        <h2>Our Gassed Winners</h2>
        <p class="mt-2">Here are just a few of our lucky competition winners!</p>
    </div>
    <div class="owl-carousel owl-theme winner_carousel">
        @foreach($winners as $winner)
        <div class="item">
            <div class="grid_item">
                <figure>
                    <img class="owl-lazy" src="{{$winner->present()->main_image}}" data-src="{{$winner->present()->main_image}}" alt="{{$winner->username}} Winner">
                </figure>
            </div>
            <!-- /grid_item -->
        </div>
        <!-- /item -->
        @endforeach
    </div>
    <!-- /products_carousel -->
    <!-- TrustBox widget - Carousel -->
    <div class="trustpilot-widget mt-4" data-locale="en-GB" data-template-id="53aa8912dec7e10d38f59f36" data-businessunit-id="5fa3f532263f0b0001b6ac27" data-style-height="140px" data-style-width="100%" data-theme="light" data-stars="4,5" data-review-languages="en">
      <a href="https://uk.trustpilot.com/review/gasmonkeycompetitions.co.uk" target="_blank" rel="noopener">Trustpilot</a>
    </div>
    <!-- End TrustBox widget -->
</div>
<!-- /container -->

resources/views/parts/_testimonials.blade.php
<div class="bg_gray">
    <div class="container margin_60">
        <div class="main_title">
        <h2>Reviews</h2>
        <p>Played our competitions? Why not leave us a review?</p>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                [review snippet goes here]
            </div>
        </div>
    </div><!-- /container -->
</div>
<!-- /bg_gray -->